_wandb:
    value:
        cli_version: 0.23.1
        e:
            h1x24rrvnv37bjfciteg1eacqka47he8:
                codePath: Tarefa_1/main_classification.py
                codePathLocal: main_classification.py
                cpu_count: 4
                cpu_count_logical: 4
                disk:
                    /:
                        total: "58581958656"
                        used: "45886152704"
                email: hugosachim@ua.pt
                executable: /usr/bin/python3
                git:
                    commit: 4e221d38d6d216a01a7ea38db1717356bb53a1f3
                    remote: https://github.com/HugoSachim/savi-2025-2026-trabalho2-grupoX.git
                host: hogu-laptop
                memory:
                    total: "8134246400"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/Tarefa_1/./main_classification.py
                python: CPython 3.12.3
                root: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/Tarefa_1
                startedAt: "2025-12-18T13:39:24.297289Z"
                writerId: h1x24rrvnv37bjfciteg1eacqka47he8
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.12.3
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 64
dataset_folder:
    value: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/datasets/mnist
experiment_full_name:
    value: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/datasets/savi_experiments/2025-12-18
experiment_path:
    value: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/datasets/savi_experiments
num_epochs:
    value: 10
percentage_examples:
    value: 1
resume_training:
    value: false
