_wandb:
    value:
        cli_version: 0.23.1
        e:
            5mzz8kuqydyq550vhdn9v951ywwzknm8:
                codePath: Tarefa_1/main_classification.py
                codePathLocal: main_classification.py
                cpu_count: 4
                cpu_count_logical: 4
                disk:
                    /:
                        total: "58581958656"
                        used: "52050391040"
                email: hugosachim@ua.pt
                executable: /usr/bin/python3
                git:
                    commit: 9442db2abe97ae8d0b40fb6bfd88384be4fd91e3
                    remote: https://github.com/HugoSachim/savi-2025-2026-trabalho2-grupoX.git
                host: hogu-laptop
                memory:
                    total: "8134242304"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/Tarefa_1/./main_classification.py
                python: CPython 3.12.3
                root: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/Tarefa_1
                startedAt: "2026-01-08T17:39:43.019215Z"
                writerId: 5mzz8kuqydyq550vhdn9v951ywwzknm8
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.12.3
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 64
dataset_folder:
    value: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/datasets/mnist
experiment_full_name:
    value: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/datasets/savi_experiments/2026-01-08
experiment_path:
    value: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/datasets/savi_experiments
num_epochs:
    value: 10
percentage_examples:
    value: 1
resume_training:
    value: false
